data:
  input:
    train: data/output/aneurist_trad_train.csv
    test: data/output/aneurist_trad_test.csv
  output: data/output/aneurist_trad_classify.csv

classifier: mlp

classifiers:
  kNN:
    k: 3
  logisticRegression:
    C: 3
    max_iter: 1000
    solver: liblinear
  mlp:
    hidden_layer_sizes: 100
    max_iter: 1000

