data:
  input:
    train: data/output/train_trad.csv
    test: data/output/val_trad.csv
  output: data/output/val_trad_classify.csv

classifier: logisticRegression

classifiers:
  kNN:
    k: 5
  logisticRegression:
    C: 10
    max_iter: 1000
    solver: liblinear
  mlp:
    hidden_layer_sizes: 25
    max_iter: 500

