data:
    input: data/aneurist_trad.csv
    output:
        train: data/output/aneurist_trad_train.csv
        test: data/output/aneurist_trad_test.csv
split:
    test_size: 0.2
    random_state: 42

outlier_removal:
    method:
    methods:
        z_score:
            threshold: 5 #Remove number to disable outlier removal 

imputation:
    method: "complete_case"

encoding:
    one_hot_cols: [PHASES_Population, PHASES_Location, FullLocation]
    orders:
        Hypertension: ["No", "Yes - Treated and Controlled", "Yes - Not Treated"]
        Smoking: ["No", "Yes: quit smoking", "Yes: still smoking"]
        ruptureStatus: ["Unruptured", "Ruptured"]

feature_selection:
    method: "correlation"
    methods:
        manual:
            features: [PHASES_Population, Hypertension, Smoking, Age, Size, EarlierSAH, PHASES_Location, ruptureStatus,Gender]
        correlation:
            threshold: 0.45

