data:
    input: data/train_trad.csv
    output:
        train: data/output/train_trad.csv
        test: data/output/val_trad.csv
split:
    test_size: 0.2
    random_state: 42

outlier_removal:
    method: 
    methods:
        z_score:
            threshold: 5

imputation:
    method: complete_case

encoding:
    one_hot_cols: [PHASES_Population, PHASES_Location, FullLocation]
    orders:
        Hypertension: ["No", "Yes - Treated and Controlled", "Yes - Not Treated"]
        Smoking: ["No", "Yes: quit smoking", "Yes: still smoking"]
        ruptureStatus: ["Unruptured", "Ruptured"]

feature_selection:
    method: correlation
    methods:
        manual:
            features: [PHASES_Population, Hypertension, Smoking, Age, Size, EarlierSAH, PHASES_Location, ruptureStatus,Gender]
        correlation:
            threshold: 0.7
        random_forest:
            n_estimators: 500 
            random_state: 0
            n_jobs: -1

